# Generated by Django 4.2.2 on 2024-01-31 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0002_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='imgs',
            field=models.ImageField(upload_to='pic'),
        ),
    ]
