# Generated by Django 4.2.2 on 2024-01-31 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0003_alter_person_imgs'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='imgs',
            new_name='img',
        ),
    ]
