# Generated by Django 4.2.2 on 2024-01-31 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0004_rename_imgs_person_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='names',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='person',
            name='img',
            field=models.ImageField(upload_to='pics'),
        ),
    ]
