# Generated by Django 4.2.2 on 2024-01-31 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0005_rename_names_person_name_alter_person_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='img',
            new_name='imgs',
        ),
        migrations.RenameField(
            model_name='person',
            old_name='name',
            new_name='names',
        ),
    ]
